---
name: Benchmark Master
on:
  push:
    branches:
      - master

jobs:
  benchmark:
    name: Run JavaScript benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: lts/*
          flags: --immutable-cache
          cache: yarn
      - name: Run benchmark
        run: yarn benchmark
      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Compare with previous commit
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "Calculate"
          tool: "benchmarkjs"
          output-file-path: benchmark/output.txt
          external-data-json-path: ./cache/benchmark-data.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: false

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "Calculate"
          tool: "benchmarkjs"
          output-file-path: benchmark/output.txt
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
