---
name: Release
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - alpha
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: "lts/*"
          flags: "--immutable-cache"
      - name: Test
        run: yarn run test
      - name: Build
        run: yarn run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run release
