---
name: Release
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: lts/*
          flags: --immutable-cache
          cache: yarn
      - name: Lint
        run: yarn run lint
      - name: Test
        run: yarn run test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run release
