---
name: Test
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint
      - name: Prettier
        run: npm run prettier
      - name: Test
        run: npm run test
      #- name: Release
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #  run: yarn run release
